### ISSUE TITLE
Wireframe Account Registraion page

### ISSUE THREAD

**Issue by evanmosby** [evanmosby/ist-303-team-3#5]
Should allow for user to:
Add their 
- full name
- email
- password

**Comment by PangAdomat** [comment]
How about the phone number and any social media link?

**Comment by evanmosby** [comment]
Should this be required for user registration, or added later in their profile?

**Comment by PangAdomat** [comment]
@evanmosby should be required when they login and can we use that information in their profile like autofill?? What do you think??
